language: c

os:
  - osx

compiler:
  - clang

before_install:
  - brew update 
  - brew install rocksdb
  - brew install nanomsg
  - brew install scons 
  - brew install libmill 

script:
  - cd src
  - scons 
